-- Earthback map_hotspots — unmet-need pins only
-- Incremental add: 24 new pins
-- Run AFTER SCHEMA_V8b_unmet_need.sql
-- Safe to run on a live database — does not touch existing rows

INSERT INTO public.map_hotspots
  (latitude, longitude, location_name, category, title,
   description, url, circle_slug, status, priority, is_visible)
VALUES
  (37.2, 36.8, 'Antakya, Hatay, Türkiye', 'unmet-need', 'Türkiye-Syria Earthquake Zone', 'Feb 2023 magnitude 7.8 earthquakes left 400,000+ in temporary container cities across Türkiye. 50,000+ permanent housing units still needed. In Syria compounded by conflict and economic collapse.', 'https://www.worldbank.org/en/news/press-release/2025/03/18/world-bank-extends-additional-funding-to-turkiye-for-construction-of-rural-homes-in-earthquake-hit-areas', 'earth-building', 'active', 3, true),
  (-15.8, 34.3, 'Blantyre Region, Malawi', 'unmet-need', 'Malawi — Cyclone Freddy Rebuild', 'Cyclone Freddy (2023) destroyed homes across 14 districts. Fewer than 15% of 150,000+ needed homes rebuilt. Abundant local timber and earth materials. Hempcrete and stabilized earth blocks well-suited.', 'https://malawi.un.org/en/237772-malawi-2023-tropical-cyclone-freddy-post-disaster-needs-assessment', 'earth-building', 'active', 3, true),
  (31.7, -8.0, 'Al Haouz Province, Morocco', 'unmet-need', 'Morocco — Atlas Mountains Earthquake Recovery', 'Sept 2023 magnitude 6.8 earthquake damaged 88,000+ structures in the High Atlas. Rural mountain communities with strong traditional adobe/rammed earth vernacular still need support restoring homes aligned with local methods.', 'https://en.yabiladi.com/articles/details/175840/post-quake-reconstruction-haouz-nears-completion.html', 'rammed-earth', 'active', 2, true),
  (31.4, 34.4, 'Gaza Strip, Palestine', 'unmet-need', 'Gaza Strip — Post-Conflict Housing Crisis', '80,000+ housing units completely destroyed. 1.9 million people need housing; reconstruction estimated to take until 2040 at current pace. Compressed earth blocks and stabilized soil construction are viable where materials can reach.', 'https://thedocs.worldbank.org/en/doc/14e309cd34e04e40b90eb19afa7b5d15-0280012024/original/Gaza-Interim-Damage-Assessment-032924-Final.pdf', 'earth-building', 'active', 3, true),
  (25.4, 68.4, 'Hyderabad, Sindh, Pakistan', 'unmet-need', 'Pakistan — Sindh Flood Recovery', '2022 monsoon floods destroyed 2.1 million homes — Sindh sustained 83% of damage. As of 2024 only 5% rebuilt. Traditional Sindhi adobe construction is highly appropriate; ADB targeting 250,000 resilient homes in 1,000 villages.', 'https://reliefweb.int/report/pakistan/1-year-pakistan-donor-conference-only-around-5-flood-damaged-homes-rebuilt', 'earth-building', 'active', 3, true),
  (8.0, 124.3, 'Marawi City, Mindanao, Philippines', 'unmet-need', 'Philippines — Marawi City Reconstruction', 'Armed conflict (2017) displaced 300,000+. Eight years later 8,200 still in temporary shelters. Only 1,500 permanent units built by UN-Habitat. Bamboo and earth infill construction well-suited to local materials and climate.', 'https://unhabitat.org.ph/rebuilding-marawi/', 'bamboo', 'active', 2, true),
  (34.5, 69.2, 'Kabul, Afghanistan', 'unmet-need', 'Afghanistan — Kabul IDP Housing Crisis', '5.7 million internally displaced. Half a million living in informal settlements with no tenure security. Traditional Afghan adobe and rammed earth construction is locally understood and climate-appropriate for the high desert plateau.', 'https://reporting.unhcr.org/operational/operations/afghanistan', 'earth-building', 'active', 3, true),
  (-8.4, 116.3, 'Lombok, West Nusa Tenggara, Indonesia', 'unmet-need', 'Indonesia — Lombok Earthquake Recovery', '2018 magnitude 7.0 earthquake damaged 73,000+ homes. Recovery ongoing. Abundant timber and volcanic stone; bamboo and earth infill construction are appropriate and culturally familiar. Post-disaster resilient design knowledge is the gap.', 'https://www.undp.org/indonesia/blog/ground-reflections-indonesias-recovery-journey', 'bamboo', 'active', 2, true),
  (21.4, 92.0, 'Cox''s Bazar, Bangladesh', 'unmet-need', 'Cox''s Bazar — Rohingya Refugee Settlements', 'World''s largest refugee settlement: 1 million+ Rohingya in fragile shelters prone to fire and cyclones. Improved bamboo and timber structures with earth-stabilized bases could significantly improve conditions with available local materials.', 'https://www.unrefugees.org/news/rohingya-crisis-explained/', 'bamboo', 'active', 3, true),
  (3.1, 40.3, 'Dadaab, Northeast Kenya', 'unmet-need', 'Kenya-Somalia — Drought Displacement', 'Successive droughts (2020-2024) displaced 2 million+. 6.9 million Somalis need humanitarian aid. Makeshift shelters from scrap materials in overcrowded camps. Stabilized earth blocks and local stone construction are viable in this climate.', 'https://reliefweb.int/report/malta/somalia-thousands-climate-displaced-individuals-being-failed-authorities-and-international-community-new-report', 'earth-building', 'active', 2, true),
  (-17.7, 168.3, 'Port Vila, Vanuatu', 'unmet-need', 'Vanuatu — Multi-Cyclone Housing Recovery', 'Hit by 12+ storms since 2012. Cyclone Harold (2020) destroyed 21,000 homes. Traditional curved timber/bamboo structures outperform concrete in cyclones. Earthback builders with cyclone-resistant design knowledge are specifically needed here.', 'https://www.sprep.org/news/prospects-and-challenges-reconstruction-after-tropical-cyclone-harold-vanuatu', 'bamboo', 'active', 2, true),
  (18.2, -73.7, 'Les Cayes, Haiti', 'unmet-need', 'Haiti — Southwest Earthquake Recovery', 'August 2021 magnitude 7.2 earthquake destroyed 130,000+ homes. As of 2024, 140,000 still need repair or rebuild. Reconstruction falls largely on individual families. Timber-reinforced adobe and local stone masonry are appropriate and affordable.', 'https://www.state.gov/reports/status-of-post-earthquake-recovery-and-development-efforts-in-haiti', 'earth-building', 'active', 3, true),
  (5.9, 10.2, 'Bamenda, Northwest Cameroon', 'unmet-need', 'Cameroon — Anglophone Crisis Displacement', 'Armed conflict since 2016 displaced 900,000 people. 500,000+ IDPs in Anglophone zones with severely limited shelter access. Ranked world''s most neglected crisis. Local timber, bamboo, and earth-block construction capacity exists and needs support.', 'https://crisisresponse.iom.int/response/cameroon-crisis-response-plan-2024', 'earth-building', 'active', 2, true),
  (3.4, -76.5, 'Cali, Colombia', 'unmet-need', 'Colombia — Venezuelan Refugee Urban Settlements', '2.8 million Venezuelan refugees; many in peri-urban informal settlements. Families pay unsustainable daily rates for inadequate shelter. Cost-effective stabilized soil and adobe construction could support incremental self-built housing with skills transfer.', 'https://reporting.unhcr.org/operational/situations/colombia-situation', 'earth-building', 'active', 2, true),
  (-16.6, 179.3, 'Vanua Levu, Fiji', 'unmet-need', 'Fiji — Cyclone Yasa Recovery & Village Relocation', 'Cyclone Yasa (2020) destroyed 8,000+ homes. Families still in tented housing years later. Rising sea levels require relocating 80+ coastal villages to higher ground — a massive community building challenge aligned with natural building approaches.', 'https://www.pacificclimatechange.net/node/29434', 'bamboo', 'active', 2, true),
  (3.5, 31.8, 'Yumbe District, Uganda', 'unmet-need', 'Uganda — Bidibidi Refugee Settlement', 'World''s third-largest refugee settlement: 270,000+ South Sudanese in 250km² area. Current thatched huts on family plots work but need improvement in durability and water resistance. Earthen bases and local materials available for upgrades.', 'https://www.unhcr.org/countries/uganda', 'earth-building', 'active', 2, true),
  (-18.9, 47.5, 'Antananarivo, Madagascar', 'unmet-need', 'Madagascar — Urban Informal Settlements', '77% of urban population lives in informal settlements. Twin cyclones (Feb 2026) affected 681,000+. 60-70% of Antananarivo housing is informal with no cyclone resistance. Cyclone-resistant earthen and local timber construction methods urgently needed.', 'https://www.unocha.org/madagascar', 'earth-building', 'active', 2, true),
  (28.0, 84.6, 'Gorkha District, Nepal', 'unmet-need', 'Nepal — Rural Mountain Housing Resilience', '2015 earthquake damaged 1M+ homes. Most rebuilt but ongoing rural mountain housing challenges persist. Stone and timber vernacular construction with seismic reinforcement is the appropriate path. Knowledge-sharing with traditional builders is the gap.', 'https://www.worldbank.org/en/country/nepal/brief/post-earthquake-reconstruction-in-nepal', 'stone-masonry', 'active', 2, true),
  (15.5, -88.0, 'San Pedro Sula, Honduras', 'unmet-need', 'Honduras — Hurricane Eta/Iota Recovery', 'Hurricanes Eta and Iota (Nov 2020) affected 92,000+ households. Regional housing deficit exceeds 3.9 million units. Bamboo, timber, and earth-block construction are well-suited to the climate. Community-based building programs are the model that works.', 'https://reliefweb.int/report/guatemala/hurricanes-eta-and-iota-6-months-later', 'bamboo', 'active', 2, true),
  (-15.1, 39.3, 'Nampula, Mozambique', 'unmet-need', 'Mozambique — Cyclone Recovery (Nampula)', 'Tropical Storm Ana (2022) destroyed 10,000 homes, displacing 121,000+ across 4 provinces. Successive storms compound recovery challenges. Stabilized earth blocks and locally sourced timber are the right materials for affordable resilient reconstruction.', 'https://reliefweb.int/report/mozambique/mozambique-tropical-storm-ana-flash-update-no2-25-january-2022', 'earth-building', 'active', 2, true),
  (-16.5, -68.2, 'El Alto, La Paz, Bolivia', 'unmet-need', 'Bolivia — La Paz Urban Informal Housing', '2023-2024 floods and landslides affected 230,000+. Informal settlements on steep slopes built without engineering guidance. Glacier retreat threatens water security. Reinforced earth-block and adobe construction is the traditional and appropriate building method.', 'https://blogs.worldbank.org/en/latinamerica/bolivia-resiliencia-urbana', 'rammed-earth', 'active', 1, true),
  (32.3, 36.2, 'Zaatari, Mafraq, Jordan', 'unmet-need', 'Jordan — Zaatari Syrian Refugee Camp', '80,000 Syrian refugees in caravans now 13 years old — 70%+ sub-standard with cracked roofs and warped walls. Passive cooling design and durable local earthen materials could make shelters viable long-term while repatriation timelines remain uncertain.', 'https://reliefweb.int/report/jordan/unhcr-jordan-zaatari-refugee-camp-factsheet-june-2025', 'earth-building', 'active', 2, true),
  (-9.5, -77.5, 'Huaraz, Ancash, Peru', 'unmet-need', 'Peru — Huaraz Glacier Flood Risk Zone', '120,000+ residents face near-certain catastrophic flooding from glacial lake melt. Informal housing in floodplains needs relocation and rebuild on safer ground. Elevated adobe construction and community risk-reduction are the local vernacular answer.', 'https://dialogue.earth/en/water/56066-in-peru-a-melting-glacier-threatens-to-flood-a-city-for-the-second-time', 'earth-building', 'active', 2, true),
  (7.3, 80.6, 'Kandy District, Sri Lanka', 'unmet-need', 'Sri Lanka — Central Highlands Flood Recovery', 'Repeated monsoon flooding and 2025 Cyclone Ditwah have displaced thousands in the Central Highlands. Rural mountain communities face ongoing housing vulnerability. Local clay and earth construction with elevated designs are appropriate and affordable.', 'https://reliefweb.int/report/sri-lanka/senehe-siyapatha-provides-houses-flood-victims', 'earth-building', 'active', 1, true);